compiles with bug in params

diff --git a/boards/modalai/voxl2/target/voxl-px4-start b/boards/modalai/voxl2/target/voxl-px4-start
--- a/boards/modalai/voxl2/target/voxl-px4-start
+++ b/boards/modalai/voxl2/target/voxl-px4-start
@@ -78,31 +78,31 @@ else
     qshell icm42688p start -s
 fi
 
-# Start Invensense ICP 101xx barometer built on to VOXL 2
-qshell icp101xx start -I -b 5
+# # Start Invensense ICP 101xx barometer built on to VOXL 2
+# qshell icp101xx start -I -b 5
 
-# Auto detect the magnetometer. If one or both of these devices
-# are not connected it will fail but not cause any harm.
-/bin/echo "Looking for qmc5883l magnetometer"
-qshell qmc5883l start -R 10 -X -b 1
-/bin/echo "Looking for ist8310 magnetometer"
-qshell ist8310 start -R 10 -X -b 1
+# # Auto detect the magnetometer. If one or both of these devices
+# # are not connected it will fail but not cause any harm.
+# /bin/echo "Looking for qmc5883l magnetometer"
+# qshell qmc5883l start -R 10 -X -b 1
+# /bin/echo "Looking for ist8310 magnetometer"
+# qshell ist8310 start -R 10 -X -b 1
 
-# GPS and magnetometer
-if [ "$GPS" != "NONE" ]; then
-	# On M0052 the GPS driver runs on the apps processor
-	if [ $PLATFORM = "M0052" ]; then
-	    gps start -d /dev/ttyHS2
-	# On M0054 and M0104 the GPS driver runs on SLPI DSP
-	else
-	    qshell gps start
-	fi
-fi
+# # GPS and magnetometer
+# if [ "$GPS" != "NONE" ]; then
+# 	# On M0052 the GPS driver runs on the apps processor
+# 	if [ $PLATFORM = "M0052" ]; then
+# 	    gps start -d /dev/ttyHS2
+# 	# On M0054 and M0104 the GPS driver runs on SLPI DSP
+# 	else
+# 	    qshell gps start
+# 	fi
+# fi
 
-# Auto detect an ncp5623c i2c RGB LED. If one isn't connected this will
-# fail but not cause any harm. 
-/bin/echo "Looking for ncp5623c RGB LED"
-qshell rgbled_ncp5623c start -X -b 1 -f 400 -a 56
+# # Auto detect an ncp5623c i2c RGB LED. If one isn't connected this will
+# # fail but not cause any harm. 
+# /bin/echo "Looking for ncp5623c RGB LED"
+# qshell rgbled_ncp5623c start -X -b 1 -f 400 -a 56
 
 # We do not change the following parameters but QGC will complain if they aren't
 # being reported as "used" by px4. "Touching" them accomplishes that.
@@ -111,8 +111,9 @@ param touch SDLOG_MODE
 
 # ESC driver
 if [ "$ESC" == "VOXL_ESC" ]; then
-    /bin/echo "Starting VOXL ESC driver"
+    /bin/echo "Starting both VOXL ESC driver"
 	qshell voxl_esc start
+	qshell voxl_esc2 start
 elif [ "$ESC" == "VOXL2_IO_PWM_ESC" ]; then
 	if [ "$RC" == "M0065_SBUS" ]; then
 		/bin/echo "Starting VOXL IO for PWM ESC with SBUS RC"
@@ -126,54 +127,54 @@ else
 fi
 
 
-# RC driver
-if [ "$RC" == "FAKE_RC_INPUT" ]; then
-    /bin/echo "Starting fake RC driver"
-    qshell rc_controller start
-elif [ "$RC" == "CRSF_RAW" ]; then
-    /bin/echo "Starting CRSF RC driver"
-    qshell crsf_rc start -d 7
-elif [ "$RC" == "CRSF_MAV" ]; then
-    /bin/echo "Starting TBS crossfire RC - MAV Mode"
-    qshell mavlink_rc_in start -m -p 7 -b 115200
-elif [ "$RC" == "SPEKTRUM" ]; then
-    /bin/echo "Starting Spektrum RC"
-	# On M0052 the RC driver runs on the apps processor
-	if [ $PLATFORM = "M0052" ]; then
-        rc_input start -d /dev/ttyHS1
-	# On M0054 and M0104 the RC driver runs on SLPI DSP
-	else
-        qshell spektrum_rc start
-	fi
-elif [ "$RC" == "GHST" ]; then
-    /bin/echo "Starting GHST RC driver"
-    qshell ghst_rc start -d 7
-elif [ "$RC" == "M0065_SBUS" ]; then
-	if [ $PLATFORM = "M0052" ]; then
-		apps_sbus start
-	elif [ "$ESC" != "VOXL2_IO_PWM_ESC" ]; then
-    	/bin/echo "Attempting to start M0065 SBUS RC driver for original M0065 FW"
-    	qshell dsp_sbus start
-		retVal=$?
-		if [ $retVal -ne 0 ]; then
-	    	/bin/echo "Starting M0065 SBUS RC driver for original M0065 FW failed"
-	    	/bin/echo "Attempting to start M0065 SBUS RC driver for new M0065 FW"
-			qshell voxl2_io start -d -p 7
-		fi
-	else
-    	/bin/echo "M0065 SBUS RC driver already started with PWM ESC start"
-	fi
-fi
+# # RC driver
+# if [ "$RC" == "FAKE_RC_INPUT" ]; then
+#     /bin/echo "Starting fake RC driver"
+#     qshell rc_controller start
+# elif [ "$RC" == "CRSF_RAW" ]; then
+#     /bin/echo "Starting CRSF RC driver"
+#     qshell crsf_rc start -d 7
+# elif [ "$RC" == "CRSF_MAV" ]; then
+#     /bin/echo "Starting TBS crossfire RC - MAV Mode"
+#     qshell mavlink_rc_in start -m -p 7 -b 115200
+# elif [ "$RC" == "SPEKTRUM" ]; then
+#     /bin/echo "Starting Spektrum RC"
+# 	# On M0052 the RC driver runs on the apps processor
+# 	if [ $PLATFORM = "M0052" ]; then
+#         rc_input start -d /dev/ttyHS1
+# 	# On M0054 and M0104 the RC driver runs on SLPI DSP
+# 	else
+#         qshell spektrum_rc start
+# 	fi
+# elif [ "$RC" == "GHST" ]; then
+#     /bin/echo "Starting GHST RC driver"
+#     qshell ghst_rc start -d 7
+# elif [ "$RC" == "M0065_SBUS" ]; then
+# 	if [ $PLATFORM = "M0052" ]; then
+# 		apps_sbus start
+# 	elif [ "$ESC" != "VOXL2_IO_PWM_ESC" ]; then
+#     	/bin/echo "Attempting to start M0065 SBUS RC driver for original M0065 FW"
+#     	qshell dsp_sbus start
+# 		retVal=$?
+# 		if [ $retVal -ne 0 ]; then
+# 	    	/bin/echo "Starting M0065 SBUS RC driver for original M0065 FW failed"
+# 	    	/bin/echo "Attempting to start M0065 SBUS RC driver for new M0065 FW"
+# 			qshell voxl2_io start -d -p 7
+# 		fi
+# 	else
+#     	/bin/echo "M0065 SBUS RC driver already started with PWM ESC start"
+# 	fi
+# fi
 
-if [ "$DISTANCE_SENSOR" == "LIGHTWARE_SF000" ]; then
-	# Make sure to set the parameter SENS_EN_SF0X to 8 for sf000/b sensor
-	qshell lightware_laser_serial start -d 7
-fi
+# if [ "$DISTANCE_SENSOR" == "LIGHTWARE_SF000" ]; then
+# 	# Make sure to set the parameter SENS_EN_SF0X to 8 for sf000/b sensor
+# 	qshell lightware_laser_serial start -d 7
+# fi
 
-if [ "$POWER_MANAGER" == "VOXLPM" ]; then
-	# APM power monitor
-	qshell voxlpm start -X -b 2
-fi
+# if [ "$POWER_MANAGER" == "VOXLPM" ]; then
+# 	# APM power monitor
+# 	qshell voxlpm start -X -b 2
+# fi
 
 # Optional distance sensor on spare i2c
 # qshell vl53l0x start -X -b 4
@@ -192,12 +193,12 @@ qshell manual_control start
 qshell control_allocator start
 qshell load_mon start
 
-# Only start the rc_update module if an actual RC driver
-# is publishing input_rc topics. Otherwise for external RC
-# over Mavlink this isn't needed.
-if [ "$RC" != "EXTERNAL" ]; then
-	qshell rc_update start
-fi
+# # Only start the rc_update module if an actual RC driver
+# # is publishing input_rc topics. Otherwise for external RC
+# # over Mavlink this isn't needed.
+# if [ "$RC" != "EXTERNAL" ]; then
+# 	qshell rc_update start
+# fi
 
 qshell commander start
 
