add params for hall sensor placement - no errors not allocating anything atm

diff --git a/boards/modalai/voxl2/target/voxl-px4-start b/boards/modalai/voxl2/target/voxl-px4-start
--- a/boards/modalai/voxl2/target/voxl-px4-start
+++ b/boards/modalai/voxl2/target/voxl-px4-start
@@ -71,16 +71,16 @@ logger start -t
 # add -e to log "from start" instead of "from arm"
 
 # # IMU (accelerometer / gyroscope)
-# if [ "$PLATFORM" == "M0104" ]; then
-#     /bin/echo "Starting IMU driver with rotation 12"
-#     qshell icm42688p start -s -R 12
-# else
-#     /bin/echo "Starting IMU driver with no rotation"
-#     qshell icm42688p start -s
-# fi
+if [ "$PLATFORM" == "M0104" ]; then
+    /bin/echo "Starting IMU driver with rotation 12"
+    qshell icm42688p start -s -R 12
+else
+    /bin/echo "Starting IMU driver with no rotation"
+    qshell icm42688p start -s
+fi
 
 # # Start Invensense ICP 101xx barometer built on to VOXL 2
-# qshell icp101xx start -I -b 5
+qshell icp101xx start -I -b 5
 
 # # Auto detect the magnetometer. If one or both of these devices
 # # are not connected it will fail but not cause any harm.
@@ -113,61 +113,61 @@ qshell tmag5273mux start -X -b 1
 param touch SYS_AUTOCONFIG
 param touch SDLOG_MODE
 
-# # ESC driver
-# if [ "$ESC" == "VOXL_ESC" ]; then
-#     /bin/echo "Starting VOXL ESC driver"
-# 	qshell voxl_esc start
-# elif [ "$ESC" == "VOXL2_IO_PWM_ESC" ]; then
-# 	if [ "$RC" == "M0065_SBUS" ]; then
-# 		/bin/echo "Starting VOXL IO for PWM ESC with SBUS RC"
-# 		qshell voxl2_io start
-# 	else
-# 		/bin/echo "Starting VOXL IO for PWM ESC without SBUS RC"
-# 		qshell voxl2_io start -e
-# 	fi
-# else
-# 	/bin/echo "No ESC type specified, not starting an ESC driver"
-# fi
+# ESC driver
+if [ "$ESC" == "VOXL_ESC" ]; then
+    /bin/echo "Starting VOXL ESC driver"
+	qshell voxl_esc start
+elif [ "$ESC" == "VOXL2_IO_PWM_ESC" ]; then
+	if [ "$RC" == "M0065_SBUS" ]; then
+		/bin/echo "Starting VOXL IO for PWM ESC with SBUS RC"
+		qshell voxl2_io start
+	else
+		/bin/echo "Starting VOXL IO for PWM ESC without SBUS RC"
+		qshell voxl2_io start -e
+	fi
+else
+	/bin/echo "No ESC type specified, not starting an ESC driver"
+fi
 
 
-# # RC driver
-# if [ "$RC" == "FAKE_RC_INPUT" ]; then
-#     /bin/echo "Starting fake RC driver"
-#     qshell rc_controller start
-# elif [ "$RC" == "CRSF_RAW" ]; then
-#     /bin/echo "Starting CRSF RC driver"
-#     qshell crsf_rc start -d 7
-# elif [ "$RC" == "CRSF_MAV" ]; then
-#     /bin/echo "Starting TBS crossfire RC - MAV Mode"
-#     qshell mavlink_rc_in start -m -p 7 -b 115200
-# elif [ "$RC" == "SPEKTRUM" ]; then
-#     /bin/echo "Starting Spektrum RC"
-# 	# On M0052 the RC driver runs on the apps processor
-# 	if [ $PLATFORM = "M0052" ]; then
-#         rc_input start -d /dev/ttyHS1
-# 	# On M0054 and M0104 the RC driver runs on SLPI DSP
-# 	else
-#         qshell spektrum_rc start
-# 	fi
-# elif [ "$RC" == "GHST" ]; then
-#     /bin/echo "Starting GHST RC driver"
-#     qshell ghst_rc start -d 7
-# elif [ "$RC" == "M0065_SBUS" ]; then
-# 	if [ $PLATFORM = "M0052" ]; then
-# 		apps_sbus start
-# 	elif [ "$ESC" != "VOXL2_IO_PWM_ESC" ]; then
-#     	/bin/echo "Attempting to start M0065 SBUS RC driver for original M0065 FW"
-#     	qshell dsp_sbus start
-# 		retVal=$?
-# 		if [ $retVal -ne 0 ]; then
-# 	    	/bin/echo "Starting M0065 SBUS RC driver for original M0065 FW failed"
-# 	    	/bin/echo "Attempting to start M0065 SBUS RC driver for new M0065 FW"
-# 			qshell voxl2_io start -d -p 7
-# 		fi
-# 	else
-#     	/bin/echo "M0065 SBUS RC driver already started with PWM ESC start"
-# 	fi
-# fi
+# RC driver
+if [ "$RC" == "FAKE_RC_INPUT" ]; then
+    /bin/echo "Starting fake RC driver"
+    qshell rc_controller start
+elif [ "$RC" == "CRSF_RAW" ]; then
+    /bin/echo "Starting CRSF RC driver"
+    qshell crsf_rc start -d 7
+elif [ "$RC" == "CRSF_MAV" ]; then
+    /bin/echo "Starting TBS crossfire RC - MAV Mode"
+    qshell mavlink_rc_in start -m -p 7 -b 115200
+elif [ "$RC" == "SPEKTRUM" ]; then
+    /bin/echo "Starting Spektrum RC"
+	# On M0052 the RC driver runs on the apps processor
+	if [ $PLATFORM = "M0052" ]; then
+        rc_input start -d /dev/ttyHS1
+	# On M0054 and M0104 the RC driver runs on SLPI DSP
+	else
+        qshell spektrum_rc start
+	fi
+elif [ "$RC" == "GHST" ]; then
+    /bin/echo "Starting GHST RC driver"
+    qshell ghst_rc start -d 7
+elif [ "$RC" == "M0065_SBUS" ]; then
+	if [ $PLATFORM = "M0052" ]; then
+		apps_sbus start
+	elif [ "$ESC" != "VOXL2_IO_PWM_ESC" ]; then
+    	/bin/echo "Attempting to start M0065 SBUS RC driver for original M0065 FW"
+    	qshell dsp_sbus start
+		retVal=$?
+		if [ $retVal -ne 0 ]; then
+	    	/bin/echo "Starting M0065 SBUS RC driver for original M0065 FW failed"
+	    	/bin/echo "Attempting to start M0065 SBUS RC driver for new M0065 FW"
+			qshell voxl2_io start -d -p 7
+		fi
+	else
+    	/bin/echo "M0065 SBUS RC driver already started with PWM ESC start"
+	fi
+fi
 
 if [ "$DISTANCE_SENSOR" == "LIGHTWARE_SF000" ]; then
 	# Make sure to set the parameter SENS_EN_SF0X to 8 for sf000/b sensor
@@ -234,7 +234,7 @@ mavlink stream -u 14556 -s ATTITUDE -r 10
 mavlink stream -u 14556 -s ATTITUDE_QUATERNION -r 10
 mavlink stream -u 14556 -s GLOBAL_POSITION_INT -r 30
 mavlink stream -u 14556 -s SCALED_PRESSURE -r 10
-mavlink stream -u 14556 -s MAG_MUX -r 1
+# mavlink stream -u 14556 -s MAG_MUX -r 1
 
 # start the slow normal mode for voxl-mavlink-server to forward to GCS
 mavlink start -x -u 14558 -o 14559 -r 100000 -n lo
